
const status_initial = {id: 1, name: "Inactivo", color: "##FFFFFF"}
const status_inactive = {id: 2, name: "Inactivo", color: "#ECECEB"}
const status_notFullfilled = {id: 3, name: "No Cumplido", color: "#FF978E"}
const status_notEstimated = {id: 4, name: "No Estimado", color: "#FFCCA3"}
const status_estimated = {id: 5, name: "Estimado", color: "#FFE7A3"}
const status_metNotValidated = {id: 6, name: "Cumplido real no validado", color: "#A3A6FF"}
const status_metValidated = {id: 7, name: "Cumplido real validado", color: "#A3F5FF"}
const status_unpayable = {id: 8, name: "No se puede pagar", color: "#FFA3FB"}
const status_payable = {id: 9, name: "Se puede pagar", color: "#E9FFA3"}
const status_paid = {id: 10, name: "Pagado", color: "#B7FFA3"}


export const STATUSES = [
  status_initial,
  status_inactive,
  status_notFullfilled,
  status_notEstimated,
  status_estimated,
  status_metNotValidated,
  status_metValidated,
  status_unpayable,
  status_payable,
  status_paid
]

export const DATA = [
  {
    "Clausulas": "Salario fijo (mensual)",
    "Importe": { amount: 100, status: status_initial},
    "january/2022": { amount: 1, status: status_initial},
    "february/2022": { amount: 1, status: status_initial},
    "march/2022": { amount: 1, status: status_initial},
    "april/2022": { amount: 1, status: status_initial},
    "may/2022": { amount: 1, status: status_initial},
    "june/2022": { amount: 1, status: status_initial},
    "july/2022": { amount: 1, status: status_initial},
    "august/2022": { amount: 1, status: status_initial},
    "september/2022": { amount: 1, status: status_initial},
    "october/2022": { amount: 1, status: status_initial},
    "november/2022": { amount: 1, status: status_initial},
    "december/2022":{ amount: 1, status: status_initial},
    "january/2023": { amount: 1, status: status_initial},
    "february/2023": { amount: 1, status: status_initial},
    "march/2023": { amount: 1, status: status_initial},
    "april/2023": { amount: 1, status: status_initial},
    "may/2023": { amount: 1, status: status_initial},
    "june/2023": { amount: 1, status: status_initial},
    "july/2023": { amount: 1, status: status_initial},
    "august/2023": { amount: 1, status: status_initial},
    "september/2023": { amount: 1, status: status_initial},
    "october/2023": { amount: 1, status: status_initial},
    "november/2023": { amount: 1, status: status_initial},
    "december/2023":{ amount: 1, status: status_initial},
    "total":""
  },
  {
    "Clausulas": "Salario fijo (restante)",
    "Importe": { amount: 100, status: status_initial},
    "january/2022": { amount: 1, status: status_initial},
    "february/2022": { amount: 2, status: status_initial},
    "march/2022": { amount: 3, status: status_initial},
    "april/2022": { amount: 4, status: status_initial},
    "may/2022": { amount: 5, status: status_initial},
    "june/2022": { amount: 6, status: status_initial},
    "july/2022": { amount: 7, status: status_initial},
    "august/2022": { amount: 8, status: status_initial},
    "september/2022": { amount: 9, status: status_initial},
    "october/2022": { amount: 10, status: status_initial},
    "november/2022": { amount: 11, status: status_initial},
    "december/2022":{ amount: 12, status: status_initial},
    "january/2023": { amount: 1, status: status_initial},
    "february/2023": { amount: 2, status: status_initial},
    "march/2023": { amount: 3, status: status_initial},
    "april/2023": { amount: 4, status: status_initial},
    "may/2023": { amount: 5, status: status_initial},
    "june/2023": { amount: 6, status: status_initial},
    "july/2023": { amount: 7, status: status_initial},
    "august/2023": { amount: 8, status: status_initial},
    "september/2023": { amount: 9, status: status_initial},
    "october/2023": { amount: 10, status: status_initial},
    "november/2023": { amount: 11, status: status_initial},
    "december/2023":{ amount: 12, status: status_initial},
    "total":""
  },
  {
    "Clausulas": "Bonus 1",
    "Importe": { amount: 100, status: status_initial},
    "january/2022": { amount: 1, status: status_initial},
    "february/2022": { amount: 2, status: status_initial},
    "march/2022": { amount: 3, status: status_initial},
    "april/2022": { amount: 4, status: status_initial},
    "may/2022": { amount: 5, status: status_initial},
    "june/2022": { amount: 6, status: status_initial},
    "july/2022": { amount: 7, status: status_initial},
    "august/2022": { amount: 8, status: status_initial},
    "september/2022": { amount: 9, status: status_initial},
    "october/2022": { amount: 10, status: status_initial},
    "november/2022": { amount: 11, status: status_initial},
    "december/2022":{ amount: 12, status: status_initial},
    "january/2023": { amount: 1, status: status_initial},
    "february/2023": { amount: 2, status: status_initial},
    "march/2023": { amount: 3, status: status_initial},
    "april/2023": { amount: 4, status: status_initial},
    "may/2023": { amount: 5, status: status_initial},
    "june/2023": { amount: 6, status: status_initial},
    "july/2023": { amount: 7, status: status_initial},
    "august/2023": { amount: 8, status: status_initial},
    "september/2023": { amount: 9, status: status_initial},
    "october/2023": { amount: 10, status: status_initial},
    "november/2023": { amount: 11, status: status_initial},
    "december/2023":{ amount: 12, status: status_initial},
    "total":""
  },
  {
    "Clausulas": "Bonus 2",
    "Importe": { amount: 100, status: status_initial},
    "january/2022": { amount: 1, status: status_initial},
    "february/2022": { amount: 2, status: status_initial},
    "march/2022": { amount: 3, status: status_initial},
    "april/2022": { amount: 4, status: status_initial},
    "may/2022": { amount: 5, status: status_initial},
    "june/2022": { amount: 6, status: status_initial},
    "july/2022": { amount: 7, status: status_initial},
    "august/2022": { amount: 8, status: status_initial},
    "september/2022": { amount: 9, status: status_initial},
    "october/2022": { amount: 10, status: status_initial},
    "november/2022": { amount: 11, status: status_initial},
    "december/2022":{ amount: 12, status: status_initial},
    "january/2023": { amount: 1, status: status_initial},
    "february/2023": { amount: 2, status: status_initial},
    "march/2023": { amount: 3, status: status_initial},
    "april/2023": { amount: 4, status: status_initial},
    "may/2023": { amount: 5, status: status_initial},
    "june/2023": { amount: 6, status: status_initial},
    "july/2023": { amount: 7, status: status_initial},
    "august/2023": { amount: 8, status: status_initial},
    "september/2023": { amount: 9, status: status_initial},
    "october/2023": { amount: 10, status: status_initial},
    "november/2023": { amount: 11, status: status_initial},
    "december/2023":{ amount: 12, status: status_initial},
    "total":""
  },
  {
    "Clausulas": "Bonus 3",
    "Importe": { amount: 100, status: status_initial},
    "january/2022": { amount: 1, status: status_initial},
    "february/2022": { amount: 2, status: status_initial},
    "march/2022": { amount: 3, status: status_initial},
    "april/2022": { amount: 4, status: status_initial},
    "may/2022": { amount: 5, status: status_initial},
    "june/2022": { amount: 6, status: status_initial},
    "july/2022": { amount: 7, status: status_initial},
    "august/2022": { amount: 8, status: status_initial},
    "september/2022": { amount: 9, status: status_initial},
    "october/2022": { amount: 10, status: status_initial},
    "november/2022": { amount: 11, status: status_initial},
    "december/2022":{ amount: 12, status: status_initial},
    "january/2023": { amount: 1, status: status_initial},
    "february/2023": { amount: 2, status: status_initial},
    "march/2023": { amount: 3, status: status_initial},
    "april/2023": { amount: 4, status: status_initial},
    "may/2023": { amount: 5, status: status_initial},
    "june/2023": { amount: 6, status: status_initial},
    "july/2023": { amount: 7, status: status_initial},
    "august/2023": { amount: 8, status: status_initial},
    "september/2023": { amount: 9, status: status_initial},
    "october/2023": { amount: 10, status: status_initial},
    "november/2023": { amount: 11, status: status_initial},
    "december/2023":{ amount: 12, status: status_initial},
    "total":""

  },
  {
    "Clausulas": "Bonus 4",
    "Importe": { amount: 100, status: status_initial},
    "january/2022": { amount: 1, status: status_initial},
    "february/2022": { amount: 2, status: status_initial},
    "march/2022": { amount: 3, status: status_initial},
    "april/2022": { amount: 4, status: status_initial},
    "may/2022": { amount: 5, status: status_initial},
    "june/2022": { amount: 6, status: status_initial},
    "july/2022": { amount: 7, status: status_initial},
    "august/2022": { amount: 8, status: status_initial},
    "september/2022": { amount: 9, status: status_initial},
    "october/2022": { amount: 10, status: status_initial},
    "november/2022": { amount: 11, status: status_initial},
    "december/2022":{ amount: 12, status: status_initial},
    "january/2023": { amount: 1, status: status_initial},
    "february/2023": { amount: 2, status: status_initial},
    "march/2023": { amount: 3, status: status_initial},
    "april/2023": { amount: 4, status: status_initial},
    "may/2023": { amount: 5, status: status_initial},
    "june/2023": { amount: 6, status: status_initial},
    "july/2023": { amount: 7, status: status_initial},
    "august/2023": { amount: 8, status: status_initial},
    "september/2023": { amount: 9, status: status_initial},
    "october/2023": { amount: 10, status: status_initial},
    "november/2023": { amount: 11, status: status_initial},
    "december/2023":{ amount: 12, status: status_initial},
    "total":""
  },
  {
    "Clausulas": "Bonus 5",
    "Importe": { amount: 100, status: status_initial},
    "january/2022": { amount: 1, status: status_initial},
    "february/2022": { amount: 2, status: status_initial},
    "march/2022": { amount: 3, status: status_initial},
    "april/2022": { amount: 4, status: status_initial},
    "may/2022": { amount: 5, status: status_initial},
    "june/2022": { amount: 6, status: status_initial},
    "july/2022": { amount: 7, status: status_initial},
    "august/2022": { amount: 8, status: status_initial},
    "september/2022": { amount: 9, status: status_initial},
    "october/2022": { amount: 10, status: status_initial},
    "november/2022": { amount: 11, status: status_initial},
    "december/2022":{ amount: 12, status: status_initial},
    "january/2023": { amount: 1, status: status_initial},
    "february/2023": { amount: 2, status: status_initial},
    "march/2023": { amount: 3, status: status_initial},
    "april/2023": { amount: 4, status: status_initial},
    "may/2023": { amount: 5, status: status_initial},
    "june/2023": { amount: 6, status: status_initial},
    "july/2023": { amount: 7, status: status_initial},
    "august/2023": { amount: 8, status: status_initial},
    "september/2023": { amount: 9, status: status_initial},
    "october/2023": { amount: 10, status: status_initial},
    "november/2023": { amount: 11, status: status_initial},
    "december/2023":{ amount: 12, status: status_initial},
    "total":""
   },
  {
    "Clausulas": "Bonus 6",
    "Importe": { amount: 100, status: status_initial},
    "january/2022": { amount: 1, status: status_initial},
    "february/2022": { amount: 2, status: status_initial},
    "march/2022": { amount: 3, status: status_initial},
    "april/2022": { amount: 4, status: status_initial},
    "may/2022": { amount: 5, status: status_initial},
    "june/2022": { amount: 6, status: status_initial},
    "july/2022": { amount: 7, status: status_initial},
    "august/2022": { amount: 8, status: status_initial},
    "september/2022": { amount: 9, status: status_initial},
    "october/2022": { amount: 10, status: status_initial},
    "november/2022": { amount: 11, status: status_initial},
    "december/2022":{ amount: 12, status: status_initial},
    "january/2023": { amount: 1, status: status_initial},
    "february/2023": { amount: 2, status: status_initial},
    "march/2023": { amount: 3, status: status_initial},
    "april/2023": { amount: 4, status: status_initial},
    "may/2023": { amount: 5, status: status_initial},
    "june/2023": { amount: 6, status: status_initial},
    "july/2023": { amount: 7, status: status_initial},
    "august/2023": { amount: 8, status: status_initial},
    "september/2023": { amount: 9, status: status_initial},
    "october/2023": { amount: 10, status: status_initial},
    "november/2023": { amount: 11, status: status_initial},
    "december/2023":{ amount: 12, status: status_initial},
    "total":""
  }
]